# OPNpool electrical

template:
  - sensor:
      - name: opnpool_power
        device_class: power
        unit_of_measurement: W
        state: '{{ states("sensor.opnpool_pump_power") | float(0)}}'

sensor:
  - platform: integration
    name: opnpool_energy
    source: sensor.opnpool_power
    unit_prefix: k
    unit_time: h
    method: trapezoidal

recorder:
  include:
    entities:
      - sensor.opnpool_power
      - sensor.opnpool_energy
